"""initial

Revision ID: 001
Revises:
Create Date: 2026-03-15 07:24:03.919549

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    sa.Enum('pending', 'running', 'completed', 'failed', name='run_status_enum').create(op.get_bind())
    sa.Enum('manual', 'auto', name='project_source_enum').create(op.get_bind())
    sa.Enum('main', 'selection', name='group_context_enum').create(op.get_bind())
    sa.Enum('manual', 'auto', name='group_source_enum').create(op.get_bind())
    op.create_table('directions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grouping_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('context', postgresql.ENUM('main', 'selection', name='group_context_enum', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'completed', 'failed', name='run_status_enum', create_type=False), nullable=False),
    sa.Column('projects_processed', sa.BigInteger(), nullable=True),
    sa.Column('groups_found', sa.BigInteger(), nullable=True),
    sa.Column('projects_in_groups', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', postgresql.ENUM('manual', 'auto', name='group_source_enum', create_type=False), nullable=False),
    sa.Column('context', postgresql.ENUM('main', 'selection', name='group_context_enum', create_type=False), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priority_directions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trl_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('is_auto_checked', sa.Boolean(), nullable=False),
    sa.Column('source', postgresql.ENUM('manual', 'auto', name='project_source_enum', create_type=False), nullable=False),
    sa.Column('direction_id', sa.UUID(), nullable=True),
    sa.Column('priority_direction_id', sa.UUID(), nullable=True),
    sa.Column('trl_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=312), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['priority_direction_id'], ['priority_directions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trl_id'], ['trl_levels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_fts', 'projects', [sa.literal_column("to_tsvector('russian', coalesce(title,'') || ' ' || coalesce(problem,'') || ' ' || coalesce(goal,'') || ' ' || coalesce(expected_result,''))")], unique=False, postgresql_using='gin')
    op.create_table('rejected_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_a_id', sa.UUID(), nullable=False),
    sa.Column('project_b_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_a_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_b_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('similarity_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_a_id', sa.UUID(), nullable=False),
    sa.Column('project_b_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('grouping_run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['grouping_run_id'], ['grouping_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_a_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_b_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_a_id', 'project_b_id', name='uq_similarity_scores_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similarity_scores')
    op.drop_table('rejected_pairs')
    op.drop_index('ix_projects_fts', table_name='projects', postgresql_using='gin')
    op.drop_table('projects')
    op.drop_table('trl_levels')
    op.drop_table('priority_directions')
    op.drop_table('groups')
    op.drop_table('grouping_runs')
    op.drop_table('directions')
    sa.Enum('manual', 'auto', name='group_source_enum').drop(op.get_bind())
    sa.Enum('main', 'selection', name='group_context_enum').drop(op.get_bind())
    sa.Enum('manual', 'auto', name='project_source_enum').drop(op.get_bind())
    sa.Enum('pending', 'running', 'completed', 'failed', name='run_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
